### ISSUE TITLE
[HW7] 1.2 SSA form

### ISSUE THREAD

**Issue by retroinspect** [swtv-kaist/cs458-fall22#24]
1. Should we provide SSA from with assert statement of 1.1?
2. Should SSA form include initialization (`int bigger = 0`)?
3. What should we provide between pseudocode or logical formula from below slide?
<img width="496" alt="Untitled" src="https://user-images.githubusercontent.com/48230029/206409301-716f9997-62a3-4081-8100-4672bddbefda.png">

**Comment by moonzoo** [comment]
> 1. Should we provide SSA from with assert statement of 1.1?

No. You don't have to write an assert statement in SSA format.  
But you need to convert the assert statement in SSA format anyway to answer 1.3 and 1.4

> 2. Should SSA form include initialization (int bigger = 0)?

Yes (for educational purpose although that initialization seems not necessary)

> 3. What should we provide between pseudocode or logical formula from below slide?

For the specific example, you should use a SSA form in the right box 
(since the SSA form below does not contain a conditional structure, which is shown in a blue font in the next slide)
